### ISSUE TITLE
9base instead mk

### ISSUE THREAD

**Issue by hachepunto** [Flores-JassoLab/ExtendAlign#2]
Is necessary to add 9base as a dependency instead mk and provide a more useful link for obtaining and configuring. Maybe https://packages.debian.org/search?keywords=9base

**Comment by xihh87** [comment]
mk can be installed both from 9base or plan9port, there are also some mk standalone implementations.

The link you are recommending is only useful for debian.

The instalation method varies if you use mac, debian or some alternate system.

Would a clarification be enough?
How would you write it?

Please try to be nice and not demanding in your tickets.
It may be a good idea to add a code of conduct.

**Comment by Flores-JassoLab** [comment]
> Is necessary to add 9base as a dependency instead mk and provide a more useful link for obtaining and configuring. Maybe https://packages.debian.org/search?keywords=9base

Hi,
Was this problem solved?
thank you
